[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build", "./node_modules/.bin/prisma generate"]

[start]
cmd = "node dist/index.js"
