ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "stripeMeteredItemId" TEXT;
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "aiGenerationsMonth" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "aiUsagePeriodStart" TIMESTAMP(3);
