import { format } from 'date-fns'

interface Snapshot {
  platform: string
  externalProfileId: string
  followers: number
  impressions: number
  engagementRate: number
}

interface PlatformBreakdown {
  totalFollowers: number
  accounts: number
}

interface ReportData {
  workspaceName: string
  generatedAt: string
  publishedPostCount: number
  snapshots: Snapshot[]
  platformBreakdown: Record<string, PlatformBreakdown>
}

const PLATFORM_COLORS: Record<string, string> = {
  INSTAGRAM: '#e1306c',
  FACEBOOK: '#1877f2',
  X: '#000000',
  TIKTOK: '#69c9d0',
  GOOGLE: '#4285f4',
}

async function getReportData(token: string): Promise<ReportData | null> {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000'
  try {
    const res = await fetch(`${apiUrl}/api/v1/reports/public/${token}`, {
      cache: 'no-store',
    })
    if (!res.ok) return null
    return (await res.json()) as ReportData
  } catch {
    return null
  }
}

export default async function PublicReportPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const data = await getReportData(token)

  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center space-y-3 px-4">
          <h1 className="text-2xl font-bold">Report not found</h1>
          <p className="text-muted-foreground text-sm">
            This report link may have expired or been deleted.
          </p>
          <a
            href="/"
            className="inline-block mt-4 text-sm text-primary underline underline-offset-4"
          >
            Go to OmniPulse
          </a>
        </div>
      </div>
    )
  }

  const totalFollowers = data.snapshots.reduce((sum, s) => sum + s.followers, 0)
  const platforms = Object.keys(data.platformBreakdown)

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b bg-card">
        <div className="max-w-4xl mx-auto px-6 py-6">
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-widest mb-1">
                Analytics Report
              </p>
              <h1 className="text-2xl font-bold">{data.workspaceName}</h1>
              <p className="text-sm text-muted-foreground mt-1">
                Generated {format(new Date(data.generatedAt), 'MMMM d, yyyy · h:mm a')}
              </p>
            </div>
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <svg
                className="h-4 w-4"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 10V3L4 14h7v7l9-11h-7z"
                />
              </svg>
              <span>Generated by OmniPulse</span>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-8 space-y-8">

        {/* Summary cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="rounded-xl border bg-card shadow-sm p-5">
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">
              Total Followers
            </p>
            <p className="text-3xl font-bold tabular-nums">
              {totalFollowers.toLocaleString()}
            </p>
            <p className="text-xs text-muted-foreground mt-1">across all accounts</p>
          </div>

          <div className="rounded-xl border bg-card shadow-sm p-5">
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">
              Posts Published
            </p>
            <p className="text-3xl font-bold tabular-nums">
              {data.publishedPostCount}
            </p>
            <p className="text-xs text-muted-foreground mt-1">last 30 days</p>
          </div>

          <div className="rounded-xl border bg-card shadow-sm p-5">
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">
              Platforms
            </p>
            <p className="text-3xl font-bold tabular-nums">{platforms.length}</p>
            <p className="text-xs text-muted-foreground mt-1">
              {platforms.map((p) => p.charAt(0) + p.slice(1).toLowerCase()).join(', ')}
            </p>
          </div>
        </div>

        {/* Platform breakdown */}
        {platforms.length > 0 && (
          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Platform Breakdown</h2>
            <div className="rounded-xl border bg-card shadow-sm overflow-hidden">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b bg-muted/30">
                    <th className="text-left px-5 py-3 text-xs font-medium text-muted-foreground">
                      Platform
                    </th>
                    <th className="text-right px-5 py-3 text-xs font-medium text-muted-foreground">
                      Accounts
                    </th>
                    <th className="text-right px-5 py-3 text-xs font-medium text-muted-foreground">
                      Total Followers
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {platforms.map((platform) => {
                    const info = data.platformBreakdown[platform]
                    const color = PLATFORM_COLORS[platform] ?? '#6b7280'
                    return (
                      <tr key={platform} className="hover:bg-muted/20 transition-colors">
                        <td className="px-5 py-3">
                          <div className="flex items-center gap-2">
                            <span
                              className="inline-block w-2.5 h-2.5 rounded-full shrink-0"
                              style={{ backgroundColor: color }}
                            />
                            <span className="font-medium">
                              {platform.charAt(0) + platform.slice(1).toLowerCase()}
                            </span>
                          </div>
                        </td>
                        <td className="px-5 py-3 text-right tabular-nums text-muted-foreground">
                          {info.accounts}
                        </td>
                        <td className="px-5 py-3 text-right tabular-nums font-medium">
                          {info.totalFollowers.toLocaleString()}
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Per-account detail */}
        {data.snapshots.length > 0 && (
          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Account Details</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {data.snapshots.map((s, i) => {
                const color = PLATFORM_COLORS[s.platform] ?? '#6b7280'
                return (
                  <div key={i} className="rounded-xl border bg-card shadow-sm p-5 space-y-3">
                    <div className="flex items-center gap-2">
                      <span
                        className="inline-block w-2.5 h-2.5 rounded-full shrink-0"
                        style={{ backgroundColor: color }}
                      />
                      <div>
                        <p className="text-sm font-semibold">
                          {s.platform.charAt(0) + s.platform.slice(1).toLowerCase()}
                        </p>
                        <p className="text-xs text-muted-foreground">{s.externalProfileId}</p>
                      </div>
                    </div>
                    <div className="grid grid-cols-3 gap-3">
                      <div>
                        <p className="text-[10px] font-medium text-muted-foreground uppercase tracking-wide">
                          Followers
                        </p>
                        <p className="text-lg font-bold tabular-nums mt-0.5">
                          {s.followers.toLocaleString()}
                        </p>
                      </div>
                      <div>
                        <p className="text-[10px] font-medium text-muted-foreground uppercase tracking-wide">
                          Impressions
                        </p>
                        <p className="text-lg font-bold tabular-nums mt-0.5">
                          {s.impressions.toLocaleString()}
                        </p>
                      </div>
                      <div>
                        <p className="text-[10px] font-medium text-muted-foreground uppercase tracking-wide">
                          Engagement
                        </p>
                        <p className="text-lg font-bold tabular-nums mt-0.5">
                          {(s.engagementRate * 100).toFixed(1)}%
                        </p>
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="border-t pt-6 text-center text-xs text-muted-foreground">
          <p>
            This report was generated by{' '}
            <a href="/" className="text-primary underline underline-offset-2">
              OmniPulse
            </a>
            . Data is a point-in-time snapshot and may not reflect real-time figures.
          </p>
        </div>
      </div>
    </div>
  )
}
